language: node_js
repo_token: 2veXDhHy96pE19Qxr8S2jOHKD6gcuyhUk
node_js:
  - "4.2"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_script:
  npm run cov
